/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.exemplos.poo.caneta;

import static java.lang.System.exit;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class frmCaneta extends javax.swing.JFrame {
    /**
     * Creates new form frmCaneta
     */
    Caneta caneta = new Caneta();
    
    public frmCaneta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jColorChooser1 = new javax.swing.JColorChooser();
        jColorChooser2 = new javax.swing.JColorChooser();
        jFileChooser1 = new javax.swing.JFileChooser();
        jFrame1 = new javax.swing.JFrame();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        CampoModelo = new javax.swing.JTextField();
        LabelCor = new javax.swing.JLabel();
        RadioBtAzul = new javax.swing.JRadioButton();
        RadioBtPreta = new javax.swing.JRadioButton();
        RadioBtVermelha = new javax.swing.JRadioButton();
        RadioBtVerde = new javax.swing.JRadioButton();
        LabelPonta = new javax.swing.JLabel();
        RadioBtPonta07 = new javax.swing.JRadioButton();
        RadioBtPonta1 = new javax.swing.JRadioButton();
        RadioBtPonta14 = new javax.swing.JRadioButton();
        RadioBtPonta16 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        CampoCarga = new javax.swing.JTextField();
        LabelCarga1 = new javax.swing.JLabel();
        RadioBtTampada = new javax.swing.JRadioButton();
        RadioBtDestampada = new javax.swing.JRadioButton();
        LabelPonta1 = new javax.swing.JLabel();
        BotaoCadastrar = new javax.swing.JButton();
        BotaoExibir = new javax.swing.JButton();
        BotaoSair = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CampoModelo.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        CampoModelo.setToolTipText("");
        CampoModelo.setBorder(javax.swing.BorderFactory.createTitledBorder("Modelo"));
        CampoModelo.setOpaque(false);
        CampoModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoModeloActionPerformed(evt);
            }
        });

        LabelCor.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        LabelCor.setText("Cor:");

        buttonGroup1.add(RadioBtAzul);
        RadioBtAzul.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        RadioBtAzul.setText("Azul");
        RadioBtAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBtAzulActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadioBtPreta);
        RadioBtPreta.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        RadioBtPreta.setText("Preta");
        RadioBtPreta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBtPretaActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadioBtVermelha);
        RadioBtVermelha.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        RadioBtVermelha.setText("Vermelha");
        RadioBtVermelha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBtVermelhaActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadioBtVerde);
        RadioBtVerde.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        RadioBtVerde.setText("Verde");
        RadioBtVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBtVerdeActionPerformed(evt);
            }
        });

        LabelPonta.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        LabelPonta.setText("Estado:");

        buttonGroup2.add(RadioBtPonta07);
        RadioBtPonta07.setText("0.7");
        RadioBtPonta07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBtPonta07ActionPerformed(evt);
            }
        });

        buttonGroup2.add(RadioBtPonta1);
        RadioBtPonta1.setText("1.0");
        RadioBtPonta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBtPonta1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(RadioBtPonta14);
        RadioBtPonta14.setText("1.4");
        RadioBtPonta14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBtPonta14ActionPerformed(evt);
            }
        });

        buttonGroup2.add(RadioBtPonta16);
        RadioBtPonta16.setText("1.6");
        RadioBtPonta16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBtPonta16ActionPerformed(evt);
            }
        });

        CampoCarga.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        CampoCarga.setToolTipText("");
        CampoCarga.setBorder(javax.swing.BorderFactory.createTitledBorder("Carga"));
        CampoCarga.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CampoCarga.setOpaque(false);
        CampoCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCargaActionPerformed(evt);
            }
        });

        LabelCarga1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        LabelCarga1.setText("%");

        buttonGroup3.add(RadioBtTampada);
        RadioBtTampada.setText("Tampada");
        RadioBtTampada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBtTampadaActionPerformed(evt);
            }
        });

        buttonGroup3.add(RadioBtDestampada);
        RadioBtDestampada.setText("Destampada");
        RadioBtDestampada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBtDestampadaActionPerformed(evt);
            }
        });

        LabelPonta1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        LabelPonta1.setText("Ponta:");

        BotaoCadastrar.setText("Cadastrar");
        BotaoCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoCadastrarMouseClicked(evt);
            }
        });
        BotaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarActionPerformed(evt);
            }
        });

        BotaoExibir.setText("Exibir");
        BotaoExibir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoExibirMouseClicked(evt);
            }
        });
        BotaoExibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoExibirActionPerformed(evt);
            }
        });

        BotaoSair.setText("Sair");
        BotaoSair.setBorderPainted(false);
        BotaoSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoSairMouseClicked(evt);
            }
        });
        BotaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(BotaoSair)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoExibir))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CampoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelCarga1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelPonta)
                                    .addComponent(LabelPonta1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(RadioBtPonta07)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RadioBtPonta1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RadioBtPonta14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RadioBtPonta16))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(RadioBtTampada)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RadioBtDestampada))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelCor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RadioBtAzul)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioBtPreta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioBtVermelha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioBtVerde)))))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BotaoCadastrar, BotaoExibir, BotaoSair});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(CampoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCarga1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(LabelCor)
                    .addComponent(RadioBtAzul)
                    .addComponent(RadioBtPreta)
                    .addComponent(RadioBtVermelha, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RadioBtVerde))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(RadioBtPonta07)
                            .addComponent(RadioBtPonta1)
                            .addComponent(RadioBtPonta14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RadioBtPonta16)
                            .addComponent(LabelPonta1))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RadioBtTampada)
                            .addComponent(LabelPonta)
                            .addComponent(RadioBtDestampada))
                        .addGap(53, 53, 53))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(BotaoExibir)
                    .addComponent(BotaoSair)
                    .addComponent(BotaoCadastrar))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {CampoCarga, CampoModelo});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {LabelCor, RadioBtAzul, RadioBtPreta, RadioBtVerde, RadioBtVermelha});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {LabelPonta, RadioBtPonta07, RadioBtPonta1, RadioBtPonta14, RadioBtPonta16});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadioBtAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBtAzulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioBtAzulActionPerformed

    private void RadioBtPretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBtPretaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioBtPretaActionPerformed

    private void RadioBtVermelhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBtVermelhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioBtVermelhaActionPerformed

    private void RadioBtVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBtVerdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioBtVerdeActionPerformed

    private void CampoModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoModeloActionPerformed

    }//GEN-LAST:event_CampoModeloActionPerformed

    private void RadioBtPonta07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBtPonta07ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioBtPonta07ActionPerformed

    private void RadioBtPonta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBtPonta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioBtPonta1ActionPerformed

    private void RadioBtPonta14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBtPonta14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioBtPonta14ActionPerformed

    private void RadioBtPonta16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBtPonta16ActionPerformed
        
    }//GEN-LAST:event_RadioBtPonta16ActionPerformed

    private void RadioBtTampadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBtTampadaActionPerformed
        int erro = caneta.tampar();
        
        if (erro > 0)
        {
            JOptionPane.showMessageDialog(this, "A caneta JÁ está tampada!");
        }
    }//GEN-LAST:event_RadioBtTampadaActionPerformed

    private void RadioBtDestampadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBtDestampadaActionPerformed
        int erro = caneta.destampar();
        
        if (erro > 0)
        {
            JOptionPane.showMessageDialog(this, "A caneta JÁ está destampada!");
        }
    }//GEN-LAST:event_RadioBtDestampadaActionPerformed

    private void CampoCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCargaActionPerformed
        
    }//GEN-LAST:event_CampoCargaActionPerformed

    private void BotaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSairActionPerformed
        exit(0);
    }//GEN-LAST:event_BotaoSairActionPerformed

    private void BotaoSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoSairMouseClicked

    }//GEN-LAST:event_BotaoSairMouseClicked

    private void BotaoExibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoExibirActionPerformed
        JOptionPane.showMessageDialog(this, caneta);
    }//GEN-LAST:event_BotaoExibirActionPerformed

    private void BotaoExibirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoExibirMouseClicked

    }//GEN-LAST:event_BotaoExibirMouseClicked

    private void BotaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarActionPerformed
        caneta.modelo = CampoModelo.getText();

        if (RadioBtAzul.isSelected())
        {
            caneta.cor = RadioBtAzul.getText();
        }
        else if (RadioBtPreta.isSelected())
        {
            caneta.cor = RadioBtPreta.getText();
        }
        else if (RadioBtVermelha.isSelected())
        {
            caneta.cor = RadioBtVermelha.getText();
        }
        else
        {
            caneta.cor = RadioBtVerde.getText();
        }

        if (RadioBtPonta07.isSelected())
        {
            caneta.ponta = Float.parseFloat(RadioBtPonta07.getText());
        }
        else if (RadioBtPonta1.isSelected())
        {
            caneta.ponta = Float.parseFloat(RadioBtPonta1.getText());
        }
        else if (RadioBtPonta14.isSelected())
        {
            caneta.ponta = Float.parseFloat(RadioBtPonta14.getText());
        }
        else
        {
            caneta.ponta = Float.parseFloat(RadioBtPonta16.getText());
        }

        caneta.carga = Integer.parseInt(CampoCarga.getText());
    }//GEN-LAST:event_BotaoCadastrarActionPerformed

    private void BotaoCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoCadastrarMouseClicked

    }//GEN-LAST:event_BotaoCadastrarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCadastrar;
    private javax.swing.JButton BotaoExibir;
    private javax.swing.JButton BotaoSair;
    private javax.swing.JTextField CampoCarga;
    private javax.swing.JTextField CampoModelo;
    private javax.swing.JLabel LabelCarga1;
    private javax.swing.JLabel LabelCor;
    private javax.swing.JLabel LabelPonta;
    private javax.swing.JLabel LabelPonta1;
    private javax.swing.JRadioButton RadioBtAzul;
    private javax.swing.JRadioButton RadioBtDestampada;
    private javax.swing.JRadioButton RadioBtPonta07;
    private javax.swing.JRadioButton RadioBtPonta1;
    private javax.swing.JRadioButton RadioBtPonta14;
    private javax.swing.JRadioButton RadioBtPonta16;
    private javax.swing.JRadioButton RadioBtPreta;
    private javax.swing.JRadioButton RadioBtTampada;
    private javax.swing.JRadioButton RadioBtVerde;
    private javax.swing.JRadioButton RadioBtVermelha;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
